version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge