services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - db
    networks:
      - internal
      - public


  redis:
    image: redis:latest
    networks:
      - internal

volumes:
  db_data:
    driver: local

networks:
  internal:
    internal: true
    name: internal_net
  public:
    name: public_net
